import type { Metadata } from "next";
import { Bai_Jamjuree, Poppins } from "next/font/google";
import Image from "next/image";
import MenuTop from "./components/shared/menu-top";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const baiJamjuree = Bai_Jamjuree({
  variable: "--font-bai-jamjuree",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${baiJamjuree.variable} bg-[#0B0D1B] text-white antialiased relative`}
      >
        <Image
          src="/images/top-overlay.png"
          className="fixed top-0 left-0 w-full h-full pointer-events-none animate-pulse-slow"
          alt="top-overlay"
          width={1000}
          height={1000}
        />
        <MenuTop />
        {children}
      </body>
    </html>
  );
}
